### ISSUE TITLE
Unrepresentable unicode characters cannot be used as : shortcode:

### ISSUE THREAD

**Issue by LionChen-WORK** [GetStream/Streamoji#1]
This does not work:

```Swift
let shortCodes: [String: EmojiSource] = [
    "\u{F0000}": .imageAsset("Image-F0000"),
]
```

This is probably a rare use case, but I am trying to use Streamoji to replace some '�' that might occur in an app.

**Comment by cardoso** [comment]
Hi @LionChen-WORK ,

Thanks for opening the issue. Do you need ":�:" to be replaced with an emoji or only "�" ?

**Comment by LionChen-WORK** [comment]
> Do you need ":�:" to be replaced with an emoji or only "�" ?

Sorry for not being clear. I am trying to get ":�:" be replaced.

Here is an example:

```Swift
class ViewController: UIViewController {

    private let emojis: [String: EmojiSource] = [
        "c": .character("😄"),
        "\u{F0000}": .character("❤️"),
    ]

    @IBOutlet weak var textView: UITextView!

    override func viewDidLoad() {
        super.viewDidLoad()

        textView.text = """
            Unpresentable character: :\u{F0000}:
            Control group: :c:
            """
        textView.configureEmojis(emojis)
    }

}
```

And this is the result: 

![streamoji-issue-1-example-1](https://user-images.githubusercontent.com/65208295/89486011-a33ddb00-d7d4-11ea-9941-80252c766703.png)

**Comment by cardoso** [comment]
@LionChen-WORK have you tried pasting the character directly in the source code?

    private let emojis: [String: EmojiSource] = [
        "c": .character("😄"),
        "�": .character("❤️"),
    ]

**Comment by cardoso** [comment]
@LionChen-WORK I just pushed version 0.1.8 which should fix your issue. I tweaked the RegEx to find unicode characters inside the shortcode. Thanks a lot for opening this issue!

**Comment by LionChen-WORK** [comment]
> have you tried pasting the character directly in the source code?

Have not tried this. But I was hoping that I could show different images for different unicodes.

> I just pushed version 0.1.8 which should fix your issue. I tweaked the RegEx to find unicode characters inside the shortcode. Thanks a lot for opening this issue!

Great work! 😀
